# src/streamlit_app.py
from __future__ import annotations

import json
import tempfile
from pathlib import Path
from typing import Tuple, List, Dict, Any, Optional

import numpy as np
import pandas as pd
import streamlit as st
from moviepy.editor import VideoFileClip

from EmotionDetector.session_analyzer import EmotionSessionAnalyzer

# Page config
st.set_page_config(
    page_title="Anti-Doomscrolling Emotion Tracker (PoC)",
    layout="wide",
)


def _make_clip_bytes(
    src_path: str,
    center_time: float,
    clip_duration: float = 10.0,
) -> bytes:
    """
    Extract a short clip around `center_time` from `src_path`
    and return as raw bytes for st.video().
    """
    video = VideoFileClip(src_path)
    start = max(center_time - clip_duration / 2.0, 0.0)
    end = min(start + clip_duration, video.duration)
    sub = video.subclip(start, end)

    with tempfile.NamedTemporaryFile(delete=False, suffix=".mp4") as tmp:
        sub.write_videofile(
            tmp.name,
            codec="libx264",
            audio=False,
            verbose=False,
            logger=None,
        )
        sub.close()
        video.close()
        with open(tmp.name, "rb") as f:
            return f.read()


@st.cache_data(show_spinner="Analyzing emotions… this may take a bit")
def _run_analysis_cached(
    video_bytes: bytes,
) -> Tuple[pd.DataFrame, List[Dict[str, Any]], str]:
    """
    Cached wrapper: write upload to temp file, run analyzer, return
    frame-level dataframe + events + temp path (for video playback).
    """
    with tempfile.NamedTemporaryFile(delete=False, suffix=".mp4") as f:
        f.write(video_bytes)
        video_path = f.name

    analyzer = EmotionSessionAnalyzer()
    df = analyzer.analyze(video_path=video_path)
    events = analyzer.get_events(df)

    return df, events, video_path


def _load_analysis_json_from_bytes(json_bytes: bytes) -> Tuple[pd.DataFrame, List[Dict[str, Any]]]:
    """
    Load unified analysis JSON produced by analyzer_app.py.

    Expected format:
    {
        "frames": [ {...}, {...}, ... ],
        "events": [ {...}, {...}, ... ],
        "summary": {...}
    }
    """
    payload = json.loads(json_bytes.decode("utf-8"))

    frames = payload.get("frames", [])
    events = payload.get("events", [])

    if not frames:
        raise ValueError("Analysis JSON does not contain any 'frames' records.")

    df = pd.DataFrame(frames)

    # sanity: ensure we have timestamp/frame_index
    if "timestamp" not in df.columns and "frame_index" in df.columns:
        # if only frame_index, we'll fake timestamps later if needed
        pass

    return df, events


def main():
    st.title("📺 Anti-Doomscrolling Emotion Tracker (PoC)")

    st.write(
        "This app can either:\n\n"
        "1. **Analyze a new combined video** (screen + webcam bottom-left 500×280), or\n"
        "2. **Load a precomputed analysis JSON** generated by the CLI analyzer.\n\n"
        "The webcam is assumed to be in the bottom-left corner; emotions are detected only there."
    )

    mode = st.radio(
        "Choose mode:",
        ["Analyze new video", "Load existing analysis (JSON)"],
        horizontal=True,
    )

    df: Optional[pd.DataFrame] = None
    events: List[Dict[str, Any]] = []
    video_bytes: Optional[bytes] = None
    video_path: Optional[str] = None

    # --- MODE 1: Analyze new video ---
    if mode == "Analyze new video":
        video_file = st.file_uploader(
            "Combined video (screen + webcam bottom-left)",
            type=["mp4", "mov", "avi", "mkv"],
            key="combined_video_uploader",
        )

        if not video_file:
            st.info("⬆️ Upload a combined video to get started.")
            return

        video_bytes = video_file.getvalue()

        # Do the heavy work (cached)
        df, events, video_path = _run_analysis_cached(video_bytes)

    # --- MODE 2: Load existing analysis JSON ---
    else:
        st.info(
            "Upload the **unified analysis JSON** generated by `analyzer_app.py` "
            "(the file ending with `_analysis.json`).\n\n"
            "Optionally, you can also upload the original video to enable playback "
            "and event clips."
        )

        json_file = st.file_uploader(
            "Analysis JSON (`*_analysis.json`)",
            type=["json"],
            key="analysis_json_uploader",
        )

        video_file_opt = st.file_uploader(
            "Original combined video (optional, for playback & clips)",
            type=["mp4", "mov", "avi", "mkv"],
            key="analysis_video_uploader",
        )

        if not json_file:
            st.info("⬆️ Upload an analysis JSON to visualize the results.")
            return

        try:
            df, events = _load_analysis_json_from_bytes(json_file.getvalue())
        except Exception as e:
            st.error(f"Failed to parse analysis JSON: {e}")
            return

        if video_file_opt is not None:
            video_bytes = video_file_opt.getvalue()
            with tempfile.NamedTemporaryFile(delete=False, suffix=".mp4") as f:
                f.write(video_bytes)
                video_path = f.name
        else:
            video_bytes = None
            video_path = None

    # At this point, we have df + events (and maybe video_bytes/video_path)

    # === Layout: video + analytics side by side ===
    col_video, col_stats = st.columns([2, 1])

    with col_video:
        st.subheader("Combined video")

        if video_bytes is not None:
            st.caption("🖥 Screen + 👤 Webcam (bottom-left 500×280)")
            st.video(video_bytes)
        else:
            st.caption("No video uploaded in this mode.")
            st.write("_Upload the original video if you want playback and event clips._")

        st.markdown("---")

        st.subheader("Engagement over time")

        if "timestamp" not in df.columns:
            st.warning("No 'timestamp' column found in analysis; engagement plot may be limited.")
        else:
            chart_df = df[["timestamp", "engagement_ma"]].rename(
                columns={"timestamp": "time (s)", "engagement_ma": "engagement"}
            )
            chart_df = chart_df.set_index("time (s)")
            st.line_chart(chart_df)

    with col_stats:
        st.subheader("Anti-doomscrolling monitor")

        avg_eng = float(df["engagement_ma"].mean()) if "engagement_ma" in df.columns else float("nan")
        high_frac = float(df["high_engagement"].mean()) if "high_engagement" in df.columns else float("nan")

        if not np.isnan(avg_eng):
            st.metric("Average engagement", f"{avg_eng:.2f}")
        else:
            st.metric("Average engagement", "N/A")

        if not np.isnan(high_frac):
            st.metric("Time in high engagement", f"{high_frac * 100:.1f} %")
        else:
            st.metric("Time in high engagement", "N/A")

        if not np.isnan(high_frac):
            if high_frac > 0.3:
                st.error(
                    "🚨 We detected extended periods of **high engagement**.\n\n"
                    "This could be a doomscrolling pattern – consider a short break."
                )
            elif high_frac > 0.1:
                st.warning(
                    "⚠️ Moderate amount of high engagement.\n\n"
                    "Might be worth checking which moments trigger you the most."
                )
            else:
                st.success("✅ Engagement is mostly moderate. No doomscrolling alarms.")
        else:
            st.info("High engagement statistics unavailable in this analysis.")

        st.markdown("---")
        st.subheader("Overall emotion distribution")

        if "dominant_emotion" in df.columns:
            emo_dist = (
                df["dominant_emotion"]
                .value_counts(normalize=True)
                .sort_values(ascending=False)
            )
            emo_df = emo_dist.rename("share").to_frame()
            st.bar_chart(emo_df)
        else:
            st.write("No `dominant_emotion` column found in analysis.")

    st.markdown("---")
    st.subheader("Big emotion events")

    if not events:
        st.write("No strong emotion spikes were detected with the current thresholds.")
    else:
        ev_df = pd.DataFrame(events)
        ev_df_display = ev_df.copy()
        if "start_time" in ev_df_display.columns:
            ev_df_display["start_time"] = ev_df_display["start_time"].round(2)
        if "end_time" in ev_df_display.columns:
            ev_df_display["end_time"] = ev_df_display["end_time"].round(2)
        if "peak_time" in ev_df_display.columns:
            ev_df_display["peak_time"] = ev_df_display["peak_time"].round(2)

        rename_map = {
            "start_time": "start (s)",
            "end_time": "end (s)",
            "peak_time": "peak (s)",
            "dominant_emotion": "emotion",
            "peak_score": "score",
        }
        ev_df_display = ev_df_display.rename(columns={k: v for k, v in rename_map.items() if k in ev_df_display.columns})

        st.dataframe(ev_df_display)

        if video_path is not None:
            st.write("Click a button to play the video around that emotion spike:")

            for i, ev in enumerate(events):
                peak_t = ev.get("peak_time", None)
                dom = ev.get("dominant_emotion", "event")
                score = ev.get("peak_score", None)

                if peak_t is None:
                    continue

                label = f"▶️ {dom} @ {peak_t:.1f}s"
                if score is not None:
                    label += f" (score {score:.2f})"

                if st.button(label, key=f"event_btn_{i}"):
                    clip_bytes = _make_clip_bytes(
                        src_path=video_path,
                        center_time=float(peak_t),
                        clip_duration=8.0,
                    )
                    st.video(clip_bytes)
        else:
            st.info("Upload the original video to enable event clip playback.")

    st.markdown("---")
    st.subheader("Per-frame emotion explorer")

    if "timestamp" not in df.columns or "frame_index" not in df.columns:
        st.write("Per-frame explorer requires `timestamp` and `frame_index` columns.")
        return

    # Slider for "current time" – approximate frame-level emotion display
    t_min = float(df["timestamp"].min())
    t_max = float(df["timestamp"].max())
    default_t = float(df["timestamp"].iloc[len(df) // 2])

    selected_t = st.slider(
        "Choose time (seconds) to inspect:",
        min_value=float(t_min),
        max_value=float(t_max),
        value=float(default_t),
        step=float(max((t_max - t_min) / 200.0, 0.1)),
    )

    # Find nearest frame to the chosen timestamp
    idx = int((df["timestamp"] - selected_t).abs().idxmin())
    row = df.iloc[idx]

    st.write(
        f"Closest frame at **{row['timestamp']:.2f} s** "
        f"(frame index {int(row['frame_index'])})"
    )

    # Emotion columns: probabilities between 0-1
    emotion_cols = [
        c
        for c in df.columns
        if c in ["angry", "disgust", "fear", "happy", "sad", "surprise", "neutral"]
    ]
    if emotion_cols:
        emo_vals = {c: float(row[c]) for c in emotion_cols}
        emo_frame_df = pd.DataFrame.from_dict(
            emo_vals, orient="index", columns=["probability"]
        )
        st.bar_chart(emo_frame_df)
    else:
        st.write("No raw emotion probability columns found for this frame.")

    st.caption(
        "Move the slider to see how the **per-frame emotion probabilities** change "
        "over time. You can cross-reference this with the video player above (if provided)."
    )


if __name__ == "__main__":
    main()
